### ISSUE TITLE
Package version 0.1.6 unavailable on repo.magento.com, causing errors during composer installation

### ISSUE THREAD

**Issue by ImAARIX** [magento/composer-dependency-version-audit-plugin#11]
Hello,
I am encountering a persistent error when attempting to reinstall packages on my local Magento 2.4.5 setup.
![image](https://github.com/user-attachments/assets/be68a4ae-3474-41e0-a086-904ee377ea8b)

Given that the version 0.1.6 of the magento/composer-dependency-version-audit-plugin package was published this morning, I suspect the issue will be resolved soon. However, I wanted to bring this to your attention in case it helps expedite the fix.
I noticed that the "Usage" paragraph in the main README mentions something similar but without any workaround, so I presume this is a known problem

Thank you!

**Comment by sidolov** [comment]
@ImAARIX thank you for the report! The issue should be resolved now
